[env:heltec_wifi_lora_32_V3]
platform = espressif32@~6.9
board = heltec_wifi_lora_32_V3
framework = arduino

monitor_speed = 115200
upload_speed = 921600

board_build.partitions = partitions_8mb_dual_ota.csv
board_build.flash_mode = qio
board_build.f_flash = 80000000L

board_build.arduino.memory_type = qio_qspi

lib_deps =
    jgromes/RadioLib@^7.0.0
    olikraus/U8g2@^2.35.30
    ayushsharma82/ElegantOTA@^3.1.7
    bblanchon/ArduinoJson@^7.3.0

board_build.filesystem = littlefs

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DELEGANTOTA_USE_ASYNC_WEBSERVER=1
    -fpermissive
